// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package org.iotexproject.antenna.grpc.iotexrpc;

public final class Rpc {
  private Rpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code iotexrpc.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>ACTION = 1;</code>
     */
    ACTION(1),
    /**
     * <code>BLOCK = 2;</code>
     */
    BLOCK(2),
    /**
     * <code>CONSENSUS = 3;</code>
     */
    CONSENSUS(3),
    /**
     * <code>BLOCK_REQUEST = 4;</code>
     */
    BLOCK_REQUEST(4),
    /**
     * <code>TEST = 10001;</code>
     */
    TEST(10001),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>ACTION = 1;</code>
     */
    public static final int ACTION_VALUE = 1;
    /**
     * <code>BLOCK = 2;</code>
     */
    public static final int BLOCK_VALUE = 2;
    /**
     * <code>CONSENSUS = 3;</code>
     */
    public static final int CONSENSUS_VALUE = 3;
    /**
     * <code>BLOCK_REQUEST = 4;</code>
     */
    public static final int BLOCK_REQUEST_VALUE = 4;
    /**
     * <code>TEST = 10001;</code>
     */
    public static final int TEST_VALUE = 10001;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return ACTION;
        case 2: return BLOCK;
        case 3: return CONSENSUS;
        case 4: return BLOCK_REQUEST;
        case 10001: return TEST;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.iotexproject.antenna.grpc.iotexrpc.Rpc.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:iotexrpc.MessageType)
  }

  public interface BlockSyncOrBuilder extends
      // @@protoc_insertion_point(interface_extends:iotexrpc.BlockSync)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 start = 2;</code>
     */
    long getStart();

    /**
     * <code>uint64 end = 3;</code>
     */
    long getEnd();
  }
  /**
   * Protobuf type {@code iotexrpc.BlockSync}
   */
  public  static final class BlockSync extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:iotexrpc.BlockSync)
      BlockSyncOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BlockSync.newBuilder() to construct.
    private BlockSync(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BlockSync() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BlockSync(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 16: {

              start_ = input.readUInt64();
              break;
            }
            case 24: {

              end_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.iotexproject.antenna.grpc.iotexrpc.Rpc.internal_static_iotexrpc_BlockSync_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.iotexproject.antenna.grpc.iotexrpc.Rpc.internal_static_iotexrpc_BlockSync_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync.class, org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync.Builder.class);
    }

    public static final int START_FIELD_NUMBER = 2;
    private long start_;
    /**
     * <code>uint64 start = 2;</code>
     */
    public long getStart() {
      return start_;
    }

    public static final int END_FIELD_NUMBER = 3;
    private long end_;
    /**
     * <code>uint64 end = 3;</code>
     */
    public long getEnd() {
      return end_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (start_ != 0L) {
        output.writeUInt64(2, start_);
      }
      if (end_ != 0L) {
        output.writeUInt64(3, end_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (start_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, start_);
      }
      if (end_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, end_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync)) {
        return super.equals(obj);
      }
      org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync other = (org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync) obj;

      if (getStart()
          != other.getStart()) return false;
      if (getEnd()
          != other.getEnd()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + START_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStart());
      hash = (37 * hash) + END_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEnd());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code iotexrpc.BlockSync}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:iotexrpc.BlockSync)
        org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSyncOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.iotexproject.antenna.grpc.iotexrpc.Rpc.internal_static_iotexrpc_BlockSync_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.iotexproject.antenna.grpc.iotexrpc.Rpc.internal_static_iotexrpc_BlockSync_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync.class, org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync.Builder.class);
      }

      // Construct using org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        start_ = 0L;

        end_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.iotexproject.antenna.grpc.iotexrpc.Rpc.internal_static_iotexrpc_BlockSync_descriptor;
      }

      @java.lang.Override
      public org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync getDefaultInstanceForType() {
        return org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync.getDefaultInstance();
      }

      @java.lang.Override
      public org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync build() {
        org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync buildPartial() {
        org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync result = new org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync(this);
        result.start_ = start_;
        result.end_ = end_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync) {
          return mergeFrom((org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync other) {
        if (other == org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync.getDefaultInstance()) return this;
        if (other.getStart() != 0L) {
          setStart(other.getStart());
        }
        if (other.getEnd() != 0L) {
          setEnd(other.getEnd());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long start_ ;
      /**
       * <code>uint64 start = 2;</code>
       */
      public long getStart() {
        return start_;
      }
      /**
       * <code>uint64 start = 2;</code>
       */
      public Builder setStart(long value) {
        
        start_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 start = 2;</code>
       */
      public Builder clearStart() {
        
        start_ = 0L;
        onChanged();
        return this;
      }

      private long end_ ;
      /**
       * <code>uint64 end = 3;</code>
       */
      public long getEnd() {
        return end_;
      }
      /**
       * <code>uint64 end = 3;</code>
       */
      public Builder setEnd(long value) {
        
        end_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 end = 3;</code>
       */
      public Builder clearEnd() {
        
        end_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:iotexrpc.BlockSync)
    }

    // @@protoc_insertion_point(class_scope:iotexrpc.BlockSync)
    private static final org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync();
    }

    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BlockSync>
        PARSER = new com.google.protobuf.AbstractParser<BlockSync>() {
      @java.lang.Override
      public BlockSync parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BlockSync(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BlockSync> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BlockSync> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.iotexproject.antenna.grpc.iotexrpc.Rpc.BlockSync getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BroadcastMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:iotexrpc.BroadcastMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 chain_id = 1;</code>
     */
    int getChainId();

    /**
     * <code>.iotexrpc.MessageType msg_type = 2;</code>
     */
    int getMsgTypeValue();
    /**
     * <code>.iotexrpc.MessageType msg_type = 2;</code>
     */
    org.iotexproject.antenna.grpc.iotexrpc.Rpc.MessageType getMsgType();

    /**
     * <code>bytes msg_body = 3;</code>
     */
    com.google.protobuf.ByteString getMsgBody();

    /**
     * <code>string peer_id = 4;</code>
     */
    java.lang.String getPeerId();
    /**
     * <code>string peer_id = 4;</code>
     */
    com.google.protobuf.ByteString
        getPeerIdBytes();

    /**
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     */
    com.google.protobuf.Timestamp getTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();
  }
  /**
   * Protobuf type {@code iotexrpc.BroadcastMsg}
   */
  public  static final class BroadcastMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:iotexrpc.BroadcastMsg)
      BroadcastMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BroadcastMsg.newBuilder() to construct.
    private BroadcastMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BroadcastMsg() {
      msgType_ = 0;
      msgBody_ = com.google.protobuf.ByteString.EMPTY;
      peerId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BroadcastMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              chainId_ = input.readUInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              msgType_ = rawValue;
              break;
            }
            case 26: {

              msgBody_ = input.readBytes();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              peerId_ = s;
              break;
            }
            case 42: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (timestamp_ != null) {
                subBuilder = timestamp_.toBuilder();
              }
              timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(timestamp_);
                timestamp_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.iotexproject.antenna.grpc.iotexrpc.Rpc.internal_static_iotexrpc_BroadcastMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.iotexproject.antenna.grpc.iotexrpc.Rpc.internal_static_iotexrpc_BroadcastMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg.class, org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg.Builder.class);
    }

    public static final int CHAIN_ID_FIELD_NUMBER = 1;
    private int chainId_;
    /**
     * <code>uint32 chain_id = 1;</code>
     */
    public int getChainId() {
      return chainId_;
    }

    public static final int MSG_TYPE_FIELD_NUMBER = 2;
    private int msgType_;
    /**
     * <code>.iotexrpc.MessageType msg_type = 2;</code>
     */
    public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <code>.iotexrpc.MessageType msg_type = 2;</code>
     */
    public org.iotexproject.antenna.grpc.iotexrpc.Rpc.MessageType getMsgType() {
      @SuppressWarnings("deprecation")
      org.iotexproject.antenna.grpc.iotexrpc.Rpc.MessageType result = org.iotexproject.antenna.grpc.iotexrpc.Rpc.MessageType.valueOf(msgType_);
      return result == null ? org.iotexproject.antenna.grpc.iotexrpc.Rpc.MessageType.UNRECOGNIZED : result;
    }

    public static final int MSG_BODY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString msgBody_;
    /**
     * <code>bytes msg_body = 3;</code>
     */
    public com.google.protobuf.ByteString getMsgBody() {
      return msgBody_;
    }

    public static final int PEER_ID_FIELD_NUMBER = 4;
    private volatile java.lang.Object peerId_;
    /**
     * <code>string peer_id = 4;</code>
     */
    public java.lang.String getPeerId() {
      java.lang.Object ref = peerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        peerId_ = s;
        return s;
      }
    }
    /**
     * <code>string peer_id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPeerIdBytes() {
      java.lang.Object ref = peerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        peerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private com.google.protobuf.Timestamp timestamp_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     */
    public boolean hasTimestamp() {
      return timestamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      return getTimestamp();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (chainId_ != 0) {
        output.writeUInt32(1, chainId_);
      }
      if (msgType_ != org.iotexproject.antenna.grpc.iotexrpc.Rpc.MessageType.UNKNOWN.getNumber()) {
        output.writeEnum(2, msgType_);
      }
      if (!msgBody_.isEmpty()) {
        output.writeBytes(3, msgBody_);
      }
      if (!getPeerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, peerId_);
      }
      if (timestamp_ != null) {
        output.writeMessage(5, getTimestamp());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (chainId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, chainId_);
      }
      if (msgType_ != org.iotexproject.antenna.grpc.iotexrpc.Rpc.MessageType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, msgType_);
      }
      if (!msgBody_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, msgBody_);
      }
      if (!getPeerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, peerId_);
      }
      if (timestamp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getTimestamp());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg)) {
        return super.equals(obj);
      }
      org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg other = (org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg) obj;

      if (getChainId()
          != other.getChainId()) return false;
      if (msgType_ != other.msgType_) return false;
      if (!getMsgBody()
          .equals(other.getMsgBody())) return false;
      if (!getPeerId()
          .equals(other.getPeerId())) return false;
      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (!getTimestamp()
            .equals(other.getTimestamp())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHAIN_ID_FIELD_NUMBER;
      hash = (53 * hash) + getChainId();
      hash = (37 * hash) + MSG_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      hash = (37 * hash) + MSG_BODY_FIELD_NUMBER;
      hash = (53 * hash) + getMsgBody().hashCode();
      hash = (37 * hash) + PEER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPeerId().hashCode();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code iotexrpc.BroadcastMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:iotexrpc.BroadcastMsg)
        org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.iotexproject.antenna.grpc.iotexrpc.Rpc.internal_static_iotexrpc_BroadcastMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.iotexproject.antenna.grpc.iotexrpc.Rpc.internal_static_iotexrpc_BroadcastMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg.class, org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg.Builder.class);
      }

      // Construct using org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        chainId_ = 0;

        msgType_ = 0;

        msgBody_ = com.google.protobuf.ByteString.EMPTY;

        peerId_ = "";

        if (timestampBuilder_ == null) {
          timestamp_ = null;
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.iotexproject.antenna.grpc.iotexrpc.Rpc.internal_static_iotexrpc_BroadcastMsg_descriptor;
      }

      @java.lang.Override
      public org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg getDefaultInstanceForType() {
        return org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg.getDefaultInstance();
      }

      @java.lang.Override
      public org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg build() {
        org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg buildPartial() {
        org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg result = new org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg(this);
        result.chainId_ = chainId_;
        result.msgType_ = msgType_;
        result.msgBody_ = msgBody_;
        result.peerId_ = peerId_;
        if (timestampBuilder_ == null) {
          result.timestamp_ = timestamp_;
        } else {
          result.timestamp_ = timestampBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg) {
          return mergeFrom((org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg other) {
        if (other == org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg.getDefaultInstance()) return this;
        if (other.getChainId() != 0) {
          setChainId(other.getChainId());
        }
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        if (other.getMsgBody() != com.google.protobuf.ByteString.EMPTY) {
          setMsgBody(other.getMsgBody());
        }
        if (!other.getPeerId().isEmpty()) {
          peerId_ = other.peerId_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int chainId_ ;
      /**
       * <code>uint32 chain_id = 1;</code>
       */
      public int getChainId() {
        return chainId_;
      }
      /**
       * <code>uint32 chain_id = 1;</code>
       */
      public Builder setChainId(int value) {
        
        chainId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 chain_id = 1;</code>
       */
      public Builder clearChainId() {
        
        chainId_ = 0;
        onChanged();
        return this;
      }

      private int msgType_ = 0;
      /**
       * <code>.iotexrpc.MessageType msg_type = 2;</code>
       */
      public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <code>.iotexrpc.MessageType msg_type = 2;</code>
       */
      public Builder setMsgTypeValue(int value) {
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.iotexrpc.MessageType msg_type = 2;</code>
       */
      public org.iotexproject.antenna.grpc.iotexrpc.Rpc.MessageType getMsgType() {
        @SuppressWarnings("deprecation")
        org.iotexproject.antenna.grpc.iotexrpc.Rpc.MessageType result = org.iotexproject.antenna.grpc.iotexrpc.Rpc.MessageType.valueOf(msgType_);
        return result == null ? org.iotexproject.antenna.grpc.iotexrpc.Rpc.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.iotexrpc.MessageType msg_type = 2;</code>
       */
      public Builder setMsgType(org.iotexproject.antenna.grpc.iotexrpc.Rpc.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.iotexrpc.MessageType msg_type = 2;</code>
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString msgBody_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes msg_body = 3;</code>
       */
      public com.google.protobuf.ByteString getMsgBody() {
        return msgBody_;
      }
      /**
       * <code>bytes msg_body = 3;</code>
       */
      public Builder setMsgBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes msg_body = 3;</code>
       */
      public Builder clearMsgBody() {
        
        msgBody_ = getDefaultInstance().getMsgBody();
        onChanged();
        return this;
      }

      private java.lang.Object peerId_ = "";
      /**
       * <code>string peer_id = 4;</code>
       */
      public java.lang.String getPeerId() {
        java.lang.Object ref = peerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          peerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string peer_id = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPeerIdBytes() {
        java.lang.Object ref = peerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          peerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string peer_id = 4;</code>
       */
      public Builder setPeerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        peerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string peer_id = 4;</code>
       */
      public Builder clearPeerId() {
        
        peerId_ = getDefaultInstance().getPeerId();
        onChanged();
        return this;
      }
      /**
       * <code>string peer_id = 4;</code>
       */
      public Builder setPeerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        peerId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp timestamp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      public boolean hasTimestamp() {
        return timestampBuilder_ != null || timestamp_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      public com.google.protobuf.Timestamp getTimestamp() {
        if (timestampBuilder_ == null) {
          return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        } else {
          return timestampBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      public Builder setTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timestamp_ = value;
          onChanged();
        } else {
          timestampBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      public Builder setTimestamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timestampBuilder_ == null) {
          timestamp_ = builderForValue.build();
          onChanged();
        } else {
          timestampBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (timestamp_ != null) {
            timestamp_ =
              com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
          } else {
            timestamp_ = value;
          }
          onChanged();
        } else {
          timestampBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      public Builder clearTimestamp() {
        if (timestampBuilder_ == null) {
          timestamp_ = null;
          onChanged();
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
        
        onChanged();
        return getTimestampFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
        if (timestampBuilder_ != null) {
          return timestampBuilder_.getMessageOrBuilder();
        } else {
          return timestamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimestampFieldBuilder() {
        if (timestampBuilder_ == null) {
          timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTimestamp(),
                  getParentForChildren(),
                  isClean());
          timestamp_ = null;
        }
        return timestampBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:iotexrpc.BroadcastMsg)
    }

    // @@protoc_insertion_point(class_scope:iotexrpc.BroadcastMsg)
    private static final org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg();
    }

    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BroadcastMsg>
        PARSER = new com.google.protobuf.AbstractParser<BroadcastMsg>() {
      @java.lang.Override
      public BroadcastMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BroadcastMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BroadcastMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BroadcastMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.iotexproject.antenna.grpc.iotexrpc.Rpc.BroadcastMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UnicastMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:iotexrpc.UnicastMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 chain_id = 1;</code>
     */
    int getChainId();

    /**
     * <code>string addr = 2;</code>
     */
    java.lang.String getAddr();
    /**
     * <code>string addr = 2;</code>
     */
    com.google.protobuf.ByteString
        getAddrBytes();

    /**
     * <code>.iotexrpc.MessageType msg_type = 3;</code>
     */
    int getMsgTypeValue();
    /**
     * <code>.iotexrpc.MessageType msg_type = 3;</code>
     */
    org.iotexproject.antenna.grpc.iotexrpc.Rpc.MessageType getMsgType();

    /**
     * <code>bytes msg_body = 4;</code>
     */
    com.google.protobuf.ByteString getMsgBody();

    /**
     * <code>string peer_id = 5;</code>
     */
    java.lang.String getPeerId();
    /**
     * <code>string peer_id = 5;</code>
     */
    com.google.protobuf.ByteString
        getPeerIdBytes();

    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    com.google.protobuf.Timestamp getTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();
  }
  /**
   * Protobuf type {@code iotexrpc.UnicastMsg}
   */
  public  static final class UnicastMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:iotexrpc.UnicastMsg)
      UnicastMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UnicastMsg.newBuilder() to construct.
    private UnicastMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UnicastMsg() {
      addr_ = "";
      msgType_ = 0;
      msgBody_ = com.google.protobuf.ByteString.EMPTY;
      peerId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UnicastMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              chainId_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              addr_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              msgType_ = rawValue;
              break;
            }
            case 34: {

              msgBody_ = input.readBytes();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              peerId_ = s;
              break;
            }
            case 50: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (timestamp_ != null) {
                subBuilder = timestamp_.toBuilder();
              }
              timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(timestamp_);
                timestamp_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.iotexproject.antenna.grpc.iotexrpc.Rpc.internal_static_iotexrpc_UnicastMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.iotexproject.antenna.grpc.iotexrpc.Rpc.internal_static_iotexrpc_UnicastMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg.class, org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg.Builder.class);
    }

    public static final int CHAIN_ID_FIELD_NUMBER = 1;
    private int chainId_;
    /**
     * <code>uint32 chain_id = 1;</code>
     */
    public int getChainId() {
      return chainId_;
    }

    public static final int ADDR_FIELD_NUMBER = 2;
    private volatile java.lang.Object addr_;
    /**
     * <code>string addr = 2;</code>
     */
    public java.lang.String getAddr() {
      java.lang.Object ref = addr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        addr_ = s;
        return s;
      }
    }
    /**
     * <code>string addr = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAddrBytes() {
      java.lang.Object ref = addr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        addr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSG_TYPE_FIELD_NUMBER = 3;
    private int msgType_;
    /**
     * <code>.iotexrpc.MessageType msg_type = 3;</code>
     */
    public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <code>.iotexrpc.MessageType msg_type = 3;</code>
     */
    public org.iotexproject.antenna.grpc.iotexrpc.Rpc.MessageType getMsgType() {
      @SuppressWarnings("deprecation")
      org.iotexproject.antenna.grpc.iotexrpc.Rpc.MessageType result = org.iotexproject.antenna.grpc.iotexrpc.Rpc.MessageType.valueOf(msgType_);
      return result == null ? org.iotexproject.antenna.grpc.iotexrpc.Rpc.MessageType.UNRECOGNIZED : result;
    }

    public static final int MSG_BODY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString msgBody_;
    /**
     * <code>bytes msg_body = 4;</code>
     */
    public com.google.protobuf.ByteString getMsgBody() {
      return msgBody_;
    }

    public static final int PEER_ID_FIELD_NUMBER = 5;
    private volatile java.lang.Object peerId_;
    /**
     * <code>string peer_id = 5;</code>
     */
    public java.lang.String getPeerId() {
      java.lang.Object ref = peerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        peerId_ = s;
        return s;
      }
    }
    /**
     * <code>string peer_id = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPeerIdBytes() {
      java.lang.Object ref = peerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        peerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private com.google.protobuf.Timestamp timestamp_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    public boolean hasTimestamp() {
      return timestamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      return getTimestamp();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (chainId_ != 0) {
        output.writeUInt32(1, chainId_);
      }
      if (!getAddrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, addr_);
      }
      if (msgType_ != org.iotexproject.antenna.grpc.iotexrpc.Rpc.MessageType.UNKNOWN.getNumber()) {
        output.writeEnum(3, msgType_);
      }
      if (!msgBody_.isEmpty()) {
        output.writeBytes(4, msgBody_);
      }
      if (!getPeerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, peerId_);
      }
      if (timestamp_ != null) {
        output.writeMessage(6, getTimestamp());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (chainId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, chainId_);
      }
      if (!getAddrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, addr_);
      }
      if (msgType_ != org.iotexproject.antenna.grpc.iotexrpc.Rpc.MessageType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, msgType_);
      }
      if (!msgBody_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, msgBody_);
      }
      if (!getPeerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, peerId_);
      }
      if (timestamp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getTimestamp());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg)) {
        return super.equals(obj);
      }
      org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg other = (org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg) obj;

      if (getChainId()
          != other.getChainId()) return false;
      if (!getAddr()
          .equals(other.getAddr())) return false;
      if (msgType_ != other.msgType_) return false;
      if (!getMsgBody()
          .equals(other.getMsgBody())) return false;
      if (!getPeerId()
          .equals(other.getPeerId())) return false;
      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (!getTimestamp()
            .equals(other.getTimestamp())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHAIN_ID_FIELD_NUMBER;
      hash = (53 * hash) + getChainId();
      hash = (37 * hash) + ADDR_FIELD_NUMBER;
      hash = (53 * hash) + getAddr().hashCode();
      hash = (37 * hash) + MSG_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      hash = (37 * hash) + MSG_BODY_FIELD_NUMBER;
      hash = (53 * hash) + getMsgBody().hashCode();
      hash = (37 * hash) + PEER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPeerId().hashCode();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code iotexrpc.UnicastMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:iotexrpc.UnicastMsg)
        org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.iotexproject.antenna.grpc.iotexrpc.Rpc.internal_static_iotexrpc_UnicastMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.iotexproject.antenna.grpc.iotexrpc.Rpc.internal_static_iotexrpc_UnicastMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg.class, org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg.Builder.class);
      }

      // Construct using org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        chainId_ = 0;

        addr_ = "";

        msgType_ = 0;

        msgBody_ = com.google.protobuf.ByteString.EMPTY;

        peerId_ = "";

        if (timestampBuilder_ == null) {
          timestamp_ = null;
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.iotexproject.antenna.grpc.iotexrpc.Rpc.internal_static_iotexrpc_UnicastMsg_descriptor;
      }

      @java.lang.Override
      public org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg getDefaultInstanceForType() {
        return org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg.getDefaultInstance();
      }

      @java.lang.Override
      public org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg build() {
        org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg buildPartial() {
        org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg result = new org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg(this);
        result.chainId_ = chainId_;
        result.addr_ = addr_;
        result.msgType_ = msgType_;
        result.msgBody_ = msgBody_;
        result.peerId_ = peerId_;
        if (timestampBuilder_ == null) {
          result.timestamp_ = timestamp_;
        } else {
          result.timestamp_ = timestampBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg) {
          return mergeFrom((org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg other) {
        if (other == org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg.getDefaultInstance()) return this;
        if (other.getChainId() != 0) {
          setChainId(other.getChainId());
        }
        if (!other.getAddr().isEmpty()) {
          addr_ = other.addr_;
          onChanged();
        }
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        if (other.getMsgBody() != com.google.protobuf.ByteString.EMPTY) {
          setMsgBody(other.getMsgBody());
        }
        if (!other.getPeerId().isEmpty()) {
          peerId_ = other.peerId_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int chainId_ ;
      /**
       * <code>uint32 chain_id = 1;</code>
       */
      public int getChainId() {
        return chainId_;
      }
      /**
       * <code>uint32 chain_id = 1;</code>
       */
      public Builder setChainId(int value) {
        
        chainId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 chain_id = 1;</code>
       */
      public Builder clearChainId() {
        
        chainId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object addr_ = "";
      /**
       * <code>string addr = 2;</code>
       */
      public java.lang.String getAddr() {
        java.lang.Object ref = addr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          addr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string addr = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAddrBytes() {
        java.lang.Object ref = addr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          addr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string addr = 2;</code>
       */
      public Builder setAddr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        addr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string addr = 2;</code>
       */
      public Builder clearAddr() {
        
        addr_ = getDefaultInstance().getAddr();
        onChanged();
        return this;
      }
      /**
       * <code>string addr = 2;</code>
       */
      public Builder setAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        addr_ = value;
        onChanged();
        return this;
      }

      private int msgType_ = 0;
      /**
       * <code>.iotexrpc.MessageType msg_type = 3;</code>
       */
      public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <code>.iotexrpc.MessageType msg_type = 3;</code>
       */
      public Builder setMsgTypeValue(int value) {
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.iotexrpc.MessageType msg_type = 3;</code>
       */
      public org.iotexproject.antenna.grpc.iotexrpc.Rpc.MessageType getMsgType() {
        @SuppressWarnings("deprecation")
        org.iotexproject.antenna.grpc.iotexrpc.Rpc.MessageType result = org.iotexproject.antenna.grpc.iotexrpc.Rpc.MessageType.valueOf(msgType_);
        return result == null ? org.iotexproject.antenna.grpc.iotexrpc.Rpc.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.iotexrpc.MessageType msg_type = 3;</code>
       */
      public Builder setMsgType(org.iotexproject.antenna.grpc.iotexrpc.Rpc.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.iotexrpc.MessageType msg_type = 3;</code>
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString msgBody_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes msg_body = 4;</code>
       */
      public com.google.protobuf.ByteString getMsgBody() {
        return msgBody_;
      }
      /**
       * <code>bytes msg_body = 4;</code>
       */
      public Builder setMsgBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes msg_body = 4;</code>
       */
      public Builder clearMsgBody() {
        
        msgBody_ = getDefaultInstance().getMsgBody();
        onChanged();
        return this;
      }

      private java.lang.Object peerId_ = "";
      /**
       * <code>string peer_id = 5;</code>
       */
      public java.lang.String getPeerId() {
        java.lang.Object ref = peerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          peerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string peer_id = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPeerIdBytes() {
        java.lang.Object ref = peerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          peerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string peer_id = 5;</code>
       */
      public Builder setPeerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        peerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string peer_id = 5;</code>
       */
      public Builder clearPeerId() {
        
        peerId_ = getDefaultInstance().getPeerId();
        onChanged();
        return this;
      }
      /**
       * <code>string peer_id = 5;</code>
       */
      public Builder setPeerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        peerId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp timestamp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
      /**
       * <code>.google.protobuf.Timestamp timestamp = 6;</code>
       */
      public boolean hasTimestamp() {
        return timestampBuilder_ != null || timestamp_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 6;</code>
       */
      public com.google.protobuf.Timestamp getTimestamp() {
        if (timestampBuilder_ == null) {
          return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        } else {
          return timestampBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 6;</code>
       */
      public Builder setTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timestamp_ = value;
          onChanged();
        } else {
          timestampBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 6;</code>
       */
      public Builder setTimestamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timestampBuilder_ == null) {
          timestamp_ = builderForValue.build();
          onChanged();
        } else {
          timestampBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 6;</code>
       */
      public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (timestamp_ != null) {
            timestamp_ =
              com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
          } else {
            timestamp_ = value;
          }
          onChanged();
        } else {
          timestampBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 6;</code>
       */
      public Builder clearTimestamp() {
        if (timestampBuilder_ == null) {
          timestamp_ = null;
          onChanged();
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 6;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
        
        onChanged();
        return getTimestampFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 6;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
        if (timestampBuilder_ != null) {
          return timestampBuilder_.getMessageOrBuilder();
        } else {
          return timestamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimestampFieldBuilder() {
        if (timestampBuilder_ == null) {
          timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTimestamp(),
                  getParentForChildren(),
                  isClean());
          timestamp_ = null;
        }
        return timestampBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:iotexrpc.UnicastMsg)
    }

    // @@protoc_insertion_point(class_scope:iotexrpc.UnicastMsg)
    private static final org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg();
    }

    public static org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UnicastMsg>
        PARSER = new com.google.protobuf.AbstractParser<UnicastMsg>() {
      @java.lang.Override
      public UnicastMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UnicastMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UnicastMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UnicastMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.iotexproject.antenna.grpc.iotexrpc.Rpc.UnicastMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iotexrpc_BlockSync_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iotexrpc_BlockSync_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iotexrpc_BroadcastMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iotexrpc_BroadcastMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iotexrpc_UnicastMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_iotexrpc_UnicastMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\trpc.proto\022\010iotexrpc\032\037google/protobuf/t" +
      "imestamp.proto\"\'\n\tBlockSync\022\r\n\005start\030\002 \001" +
      "(\004\022\013\n\003end\030\003 \001(\004\"\233\001\n\014BroadcastMsg\022\020\n\010chai" +
      "n_id\030\001 \001(\r\022\'\n\010msg_type\030\002 \001(\0162\025.iotexrpc." +
      "MessageType\022\020\n\010msg_body\030\003 \001(\014\022\017\n\007peer_id" +
      "\030\004 \001(\t\022-\n\ttimestamp\030\005 \001(\0132\032.google.proto" +
      "buf.Timestamp\"\247\001\n\nUnicastMsg\022\020\n\010chain_id" +
      "\030\001 \001(\r\022\014\n\004addr\030\002 \001(\t\022\'\n\010msg_type\030\003 \001(\0162\025" +
      ".iotexrpc.MessageType\022\020\n\010msg_body\030\004 \001(\014\022" +
      "\017\n\007peer_id\030\005 \001(\t\022-\n\ttimestamp\030\006 \001(\0132\032.go" +
      "ogle.protobuf.Timestamp*^\n\013MessageType\022\013" +
      "\n\007UNKNOWN\020\000\022\n\n\006ACTION\020\001\022\t\n\005BLOCK\020\002\022\r\n\tCO" +
      "NSENSUS\020\003\022\021\n\rBLOCK_REQUEST\020\004\022\t\n\004TEST\020\221NB" +
      "(\n&org.iotexproject.antenna.grpc.iotexrp" +
      "cb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_iotexrpc_BlockSync_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_iotexrpc_BlockSync_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iotexrpc_BlockSync_descriptor,
        new java.lang.String[] { "Start", "End", });
    internal_static_iotexrpc_BroadcastMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_iotexrpc_BroadcastMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iotexrpc_BroadcastMsg_descriptor,
        new java.lang.String[] { "ChainId", "MsgType", "MsgBody", "PeerId", "Timestamp", });
    internal_static_iotexrpc_UnicastMsg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_iotexrpc_UnicastMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_iotexrpc_UnicastMsg_descriptor,
        new java.lang.String[] { "ChainId", "Addr", "MsgType", "MsgBody", "PeerId", "Timestamp", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
